version: "3.9"
   
services:

  auth_server:
    build: ./auth-server/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./auth-server:/code
    ports:
      - "8000:8000"

  resource_server:
    build: ./resource-server/
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./auth-server:/code
    ports:
      - "8001:8001"